### ISSUE TITLE
neuralprophet Roadmap

### ISSUE THREAD

**Issue by AlbertoAlmuinha** [AlbertoAlmuinha/neuralprophet#1]
# Project Roadmap

- [X] Create Package Structure
- [X] Develop `neural_prophet` R function
- [X] Create Tests
- [X] Automate Tests with Github Actions
- [X] Make README
- [ ] Add Vignette
- [ ] Make Hex Logo
- [ ] Make PkgDown Web
- [ ] Transfer to Modeltime/Business Science
